---
- include_tasks: "install.{{ ansible_os_family | lower }}.yml"

- name: Create dirs
  file:
    state: directory
    path: "{{ item.path }}"
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    recurse: "{{ item.recurse | default(omit) }}"
    mode: 0755
  with_items:
    - path: "{{ openresty_base_dir }}"

    - path: "{{ openresty_pid_dir }}"
      recurse: true

    - path: "{{ openresty_log_dir }}"
      owner: "{{ openresty_server_user }}"
      group: "{{ openresty_server_group }}"

    - path: "{{ openresty_conf_dir }}"
    - path: "{{ openresty_base_dir }}/sites-enabled"

    - path: "{{ openresty_ssl_key_dir }}"
    - path: "{{ openresty_ssl_cert_dir }}"
    - path: "{{ openresty_ssl_csr_dir }}"
