---

- name: verify nginx
  command: "{{ openresty_server_pkg }} -c {{ openresty_base_dir }}/nginx.conf -t"

- name: reload nginx
  service:
    name: "{{ openresty_server_pkg }}"
    state: reloaded

- name: restart nginx
  service:
    name: "{{ openresty_server_pkg }}"
    state: restarted